In [2]:
import torch

In [10]:
a = torch.tensor([1,2,3])

In [11]:
a.dtype

torch.int64

In [12]:
a

tensor([1, 2, 3])

In [13]:
a.ndim

1

In [16]:
b = torch.tensor([[1,2,3],[4,5,6]])

In [17]:
b.ndim

2

In [18]:
b.shape

torch.Size([2, 3])

In [ ]:
na = torch.randn(3,4)

In [11]:
ra = torch.rand_like(na)

In [12]:
ra.shape

torch.Size([3, 4])

In [16]:
va = ra.view(2,3,2)

In [17]:
va.shape

torch.Size([2, 3, 2])

In [19]:
va

tensor([[[0.3557, 0.2996],
         [0.2639, 0.9852],
         [0.9148, 0.3173]],

        [[0.9128, 0.2256],
         [0.2809, 0.7640],
         [0.4526, 0.0131]]])

In [18]:
va.view(6,2)

tensor([[0.3557, 0.2996],
        [0.2639, 0.9852],
        [0.9148, 0.3173],
        [0.9128, 0.2256],
        [0.2809, 0.7640],
        [0.4526, 0.0131]])

In [22]:
va[0][0][0].item()

0.35565268993377686